export default {
  // Basic Tags
  M3U: '#EXTM3U',
  VERSION: '#EXT-X-VERSION:',

  // Media Segment Tags
  INF: '#EXTINF:',
  BYTERANGE: '#EXT-X-BYTERANGE:',
  DISCONTINUITY: '#EXT-X-DISCONTINUITY',
  KEY: '#EXT-X-KEY',
  MAP: '#EXT-X-MAP',
  PROGRAM_DATE_TIME: '#EXT-X-PROGRAM-DATE-TIME:',

  // Media Playlist Tags
  TARGETDURATION: '#EXT-X-TARGETDURATION:',
  MEDIA_SEQUENCE: '#EXT-X-MEDIA-SEQUENCE:',
  DISCONTINUITY_SEQUENCE: '#EXT-X-DISCONTINUITY-SEQUENCE:',
  ENDLIST: '#EXT-X-ENDLIST',
  PLAYLIST_TYPE: '#EXT-X-PLAYLIST-TYPE:',
  START: '#EXT-X-START:',

  // Master Playlist Tags
  MEDIA: '#EXT-X-MEDIA:',
  STREAM_INF: '#EXT-X-STREAM-INF:'
};
